version: "3.9"

x-defaults: &default
  restart: unless-stopped
#  使用当前目录的 Dockerfile 来构建 docker 镜像
  build: .
  # build from specific image
  image : tony/ros2:demo
  volumes:
    - /home/tony/ROS2_ws:/root/ros2_ws
    # function along with"- DISPLAY=unix$DISPLAY" to enable Qt 
    - /tmp/.X11-unix:/tmp/.X11-unix
  networks:
    - default
    
services:
  my-project:
    <<: *default
    container_name: ros2_project
    hostname: "ros2_project"
    user: root
    working_dir: /root/ros2_ws

#   同时通过 tailf 命令保持 container 不要退出的状态
    command:
      bash -c "tail -f /dev/null"
    environment:
      - DISPLAY=unix$DISPLAY

