version: "3.9"
services:
  realsense_ros2_service:
    
    restart: on-failure
    #  使用当前目录的 Dockerfile 来构建 docker 镜像
    build: .
    # build from specific image
    image : tony/ros2:humble-realsense
    volumes:
      - /home/tony/2ROS2workspace:/root/2ROS2workspace
      - /dev:/dev
      - /sys/devices:/sys/devices
      # function along with"- DISPLAY=unix$DISPLAY" to enable Qt 
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    container_name: ros2_realsense
    hostname: "ros2_realsense"
    user: root
    privileged: true
    working_dir: /root/2ROS2workspace
#   同时通过 tailf 命令保持 container 不要退出的状态
    command:
      bash -c "tail -f /dev/null"
    environment:
      - DISPLAY=unix$DISPLAY
    ports:
      - 4000:4000
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
      
