version: "3.9"
services:
  ros2_service:

    container_name: ubuntu_ui
    hostname: "tony"

    restart: on-failure
    #  使用当前目录的 Dockerfile 来构建 docker 镜像
    build: .
    # build from specific image
    image : tony/ubuntu:22.04
    volumes:
      - /home/tony/2ROS2workspace:/home/docker
      - /dev:/dev
      # function along with"- DISPLAY=unix$DISPLAY" to enable Qt 
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - default
    user: docker
    privileged: true
    working_dir: /home/dokcer
    #   同时通过 tailf 命令保持 container 不要退出的状态
    command:
      bash -c "tail -f /dev/null"
    environment:
      - DISPLAY=unix$DISPLAY  
    ports:
      - 5000:5000

 #记得在宿主机bash:   xhost +   

