version: "3.9"
    
services:
  ros2_service:
    restart: on-failure
    #  使用当前目录的 Dockerfile 来构建 docker 镜像
    build: .
    # build from specific image
    image : tony/ros2:humble-basic
    volumes:
      - /home/tony/2ROS2workspace:/root/2ROS2workspace
      - /dev:/dev
      # function along with"- DISPLAY=unix$DISPLAY" to enable Qt 
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - default
    container_name: ROS2
    hostname: "ROS2_project"
    user: root
    working_dir: /root/2ROS2workspace
    ports:
      - 3000:3000
#   同时通过 tailf 命令保持 container 不要退出的状态
    command:
      bash -c "tail -f /dev/null"
    environment:
      - DISPLAY=unix$DISPLAY

